name: CI/CD Gradle

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

env:
  PIPELINE_ACTION_SHA: 7066db745875c64770e217e3e1c769dde0dfee99

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Build Parameters
        uses: JustSiHeshteger/pipeline-action@${{ env.PIPELINE_SHA }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Build
        uses: JustSiHeshteger/pipeline-action/build@${{ env.PIPELINE_SHA }}

  test:
    name: Test App
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Test
        uses: JustSiHeshteger/pipeline-action/test@${{ env.PIPELINE_SHA }}

  sonar:
    name: SonarCloud Analyze
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Sonar Run
        uses: JustSiHeshteger/pipeline-action/sonar@${{ env.PIPELINE_SHA }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: [build, test, sonar]
    steps:
      - name: Run Deploy
        uses: JustSiHeshteger/pipeline-action/deploy@${{ env.PIPELINE_SHA }}