name: SonarQube

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build App
    uses: ./.github/workflows/build.yml

  test:
    name: Test App
    uses: ./.github/workflows/test.yml
    needs: build

  sonarqube:
    name: SonarCloud Analyze
    uses: ./.github/workflows/sonarqube.yml
    needs: build
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy App
    uses: ./.github/workflows/deploy.yml
    needs: [ build, test, sonarqube ]