name: CI/CD Gradle

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Echo
        uses: JustSiHeshteger/pipeline-action@v1
        with:
          java_version: '17'
          java_distributor: 'zulu'
          working_directory: 'my_directory'
        env: SONAR_TOKEN ${{ secrets.SONAR_TOKEN }}

      - name: Build and Test App
        uses: JustSiHeshteger/pipeline-action/build@v1

#  build:
#    name: Build App
#    uses: ./.github/workflows/build.yml
#
#  test:
#    name: Test App
#    uses: ./.github/workflows/test.yml
#    needs: build
#
#  sonarqube:
#    name: SonarCloud Analyze
#    uses: ./.github/workflows/sonarqube.yml
#    needs: build
#    secrets:
#      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#
#  deploy:
#    name: Deploy App
#    uses: ./.github/workflows/deploy.yml
#    needs: [ build, test, sonarqube ]