name: CI/CD Gradle

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
#      - name: Build Parameters
#        uses: JustSiHeshteger/pipeline-action@v1
#        with:
#          java_version: '21'
#          java_distributor: 'temurin'
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Build
        uses: JustSiHeshteger/pipeline-action/build@v1

  test:
    name: Test App
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Test
        uses: JustSiHeshteger/pipeline-action/test@v1

  sonar:
    name: SonarCloud Analyze
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Sonar Run
        uses: JustSiHeshteger/pipeline-action/sonar@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: [build, test, sonar]
    steps:
      - name: Run Deploy
        uses: JustSiHeshteger/pipeline-action/deploy@v1